# Generated by Django 5.2.7 on 2025-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('fees', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('trainer_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
