# Generated by Django 5.2.7 on 2025-10-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
